spring:
  
  # format
  jackson:
    property-naming-strategy: SNAKE_CASE

  # jdbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  # data redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: 1

  # jpa
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: false
        show_sql: true
        use_sql_comments: false
    open-in-view: false

# server
server:
  port: ${SERVER_PORT:8080}
  tomcat:
    connection-timeout: 10s

# logging
logging:
  level:
    root: info