FROM openjdk:8-jdk-alpine as builder
WORKDIR application
ARG JAR_FILE=/maeumgagym-infrastructure/build/libs/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

ARG PROFILE
ENV PROFILE ${PROFILE}

ARG DB_USERNAME
ENV DB_USERNAME ${DB_USERNAME}

ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}

ARG DB_URL
ENV DB_URL ${DB_URL}

ARG JWT_SECRET_KEY
ENV JWT_SECRET_KEY ${JWT_SECRET_KEY}

ARG JWT_ACCESS_EXP
ENV JWT_ACCESS_EXP ${JWT_ACCESS_EXP}

ARG JWT_REFRESH_EXP
ENV JWT_REFRESH_EXP ${JWT_REFRESH_EXP}

ARG JWT_HEADER
ENV JWT_HEADER ${JWT_HEADER}

ARG JWT_PREFIX
ENV JWT_PREFIX ${JWT_PREFIX}

ARG GRANT_TYPE
ENV GRANT_TYPE ${GRANT_TYPE}

ARG CLIENT_ID
ENV CLIENT_ID ${CLIENT_ID}

ARG REDIS_HOST
ENV REDIS_HOST ${REDIS_HOST}

ARG REDIS_PORT
ENV REDIS_PORT ${REDIS_PORT}

ARG FILE_SERVER_SECRET_KEY
ENV FILE_SERVER_SECRET_KEY ${FILE_SERVER_SECRET_KEY}

ARG FILE_SERVER_URL_1
ENV FILE_SERVER_URL_1 ${FILE_SERVER_URL_1}

ARG FILE_SERVER_URL_2
ENV FILE_SERVER_URL_2 ${FILE_SERVER_URL_2}

ARG SUFFIX_PATH
ENV SUFFIX_PATH ${SUFFIX_PATH}

ARG SWAGGER_PATH
ENV SWAGGER_PATH ${SWAGGER_PATH}

ARG SWAGGER_UI_PATH
ENV SWAGGER_UI_PATH ${SWAGGER_UI_PATH}

EXPOSE 8080

FROM openjdk:17
WORKDIR application
COPY --from=builder application/dependencies/ ./
COPY --from=builder application/spring-boot-loader/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/application/ ./

ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
