jwt:
  secretKey: ${JWT_SECRET_KEY:asdjfkasdhfjkashdfkashdfkahsdjkfahskdf}
  accessExpiredExp: ${JWT_ACCESS_EXP:1800000}
  refreshExpiredExp: ${JWT_REFRESH_EXP:432000000}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer}

kakao:
    grantType: authorization_code
    clientId: 6e50e797700d3b80c2a249091c3ca387
    redirectUri: http://localhost:8080/app/login/kakao
