spring:
    profiles:
        active: local
        group:
            local: "local-config, jwt, file, swagger"
            prod: "prod-config, prod-datasource, jwt, log, redis, file, swagger"
            stag: "stag-config, stag-datasource, jwt, log, redis, file, swagger"

    # format
    jackson:
        property-naming-strategy: SNAKE_CASE

# server
server:
    tomcat:
        threads:
            max: 200
            min-spare: 10
        max-connections: 8192
        accept-count: 100
        connection-timeout: 20000
