spring:
    config:
        activate:
            on-profile: local-config

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: ture
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                legacy_limit_handler: true
        open-in-view: false

    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3306/maeumgagym}
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

server:
    domain:
        front-domain: ${FRONT_LOCAL:http://localhost:3000}
        back-domain: ${BACK_LOCAL:http://localhost:8080}
    port: ${SERVER_PORT:8080}

management:
    endpoint:
        health:
            show-details: always

redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

logging:
    level:
        root: info
