spring:
    config:
        activate:
            on-profile: prod

management:
    endpoint:
        health:
            show-details: when_authorized

server:
    domain:
        front-domain: ${FRONT_DOMAIN}
        back-domain: ${BACK_DOMAIN}
    servlet:
        context-path: /maeumgagym

csrf:
    header: ${CSRF_HEADER:X-XSRF-TOKEN}
    cookie: ${CSRF_COOKIE:XSRF-TOKEN}
    parameter: ${CSRF_PARAMETER:_csrf}
