spring:
  
  # format
  jackson:
    property-naming-strategy: SNAKE_CASE

  # jdbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # jpa
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: false
        show_sql: true
        use_sql_comments: false
    open-in-view: false

# server
server:
    port: ${SERVER_PORT:8080}
    tomcat:
      connection-timeout: 10s
    servlet:
        context-path: /maeumgagym

# logging
logging:
    level:
        root: info

jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExpiredExp: ${JWT_ACCESS_EXP}
    refreshExpiredExp: ${JWT_REFRESH_EXP}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}

# data redis
redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

file:
    secret-key: ${FILE_SERVER_SECRET_KEY}
    url-1: ${FILE_SERVER_URL_1}
    url-2: ${FILE_SERVER_URL_2}
    suffixPath: ${SUFFIX_PATH}

springdoc:
    api-docs:
        path: ${SWAGGER_PATH:/docs}
    swagger-ui:
        path: ${SWAGGER_UI_PATH:/swagger-ui}
        display-request-duration: true
    cache:
        disabled: true
