spring:
    config:
        activate:
            on-profile: jwt

jwt:
    secret-key: ${JWT_SECRET_KEY:maeumgaGym$ecret|<ey#%!&}
    access-expired-exp: ${JWT_ACCESS_EXP:7200000}
    refresh-expired-exp: ${JWT_REFRESH_EXP:604800000}
    header: ${JWT_HEADER:Authorization}
    prefix: ${JWT_PREFIX:Bearer }
