spring:
  
  # format
  jackson:
    property-naming-strategy: SNAKE_CASE

  # jdbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/maeum}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}

  # jpa
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: false
        show_sql: true
        use_sql_comments: false
    open-in-view: false

# server
server:
  port: ${SERVER_PORT:8080}
  tomcat:
    connection-timeout: 10s

# logging
logging:
    level:
        root: info

jwt:
    secretKey: ${JWT_SECRET_KEY:asdjfkasdhfjkashdfkashdfkahsdjkfahskdf}
    accessExpiredExp: ${JWT_ACCESS_EXP:1800000}
    refreshExpiredExp: ${JWT_REFRESH_EXP:432000000}
    header: ${JWT_HEADER:Authorization}
    prefix: ${JWT_PREFIX:Bearer}

kakao:
    grantType: ${GRANT_TYPE}
    clientId: ${CLIENT_ID}

# data redis
redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

file:
    secret-key: ${FILE_SERVER_SECRET_KEY}
    url-1: ${FILE_SERVER_URL_1}
    url-2: ${FILE_SERVER_URL_2}
    suffixPath: ${SUFFIX_PATH}

springdoc:
    api-docs:
        path: ${SWAGGER_PATH:/docs}
    swagger-ui:
        path: ${SWAGGER_UI_PATH:/swagger-ui}
        display-request-duration: true
    cache:
        disabled: true
