object DependencyVersions {
    const val MINIO_VERSION = "8.3.2"
    const val JACKSON_VERSION = "2.10.3"
    const val MYSQL_VERSION = "8.0.28"
    const val SENTRY_VERSION = "6.2.1"
    const val JSON_VERSION = "20200518"
    const val JWT_VERSION = "0.9.1"
    const val SPRING_CLOUD_VERSION = "2021.0.5"
    const val LOGGER_VERSION = "2.0.10"
    const val SPRING_TRANSACTION = "5.3.22"
    const val QUERY_DSL_VERSION = "5.0.0"
    const val MOCKK_VERSION = "1.13.3"
    const val OPEN_API_VERSION = "1.6.11"
    const val SWAGGER_VERSION = "2.9.2"
}
