direction: down
vars: {
  implementsConnectionLabel: implements
  dependencyConnectionLabel: dependency
}

classes: {
  ImplementsConnection: {
    style.stroke-dash: 3
    target-arrowhead.style.filled: false
    label: implements
  }

  DependencyConnection: {
    label: dependency
  }
}

presentation: Presentation {
  style: {
    fill: "#F5EEC4"
    stroke: "#F5E162"
  }

  controller: "<<Kotlin Class>>\nController"
}

presentation.controller -> core.useCase: {class: DependencyConnection}

core: Core {
  style: {
    fill: "#C4F5C4"
    stroke: "#62F562"
  }

  useCase: "<<Interface>>\nIn port\nUseCase"
  infraPort: "<<Interface>>\nOut port\nInfra Port"
  persistencePort: "<<Interface>>\nOut port\nPersistence Port"
  model: "<<Data Class>>\nModel"

  service: "[internal]\n<<Kotlin Class>>\nUseCase Implements\nService" {
    style: {
      stroke-width: 5
    }
  }

  service -> useCase: {class: ImplementsConnection}
  service -> persistencePort: {class: DependencyConnection}
  service -> infraPort: {class: DependencyConnection}
}

application: Application {
  style: {
    fill: "#C4DDF5"
    stroke: "#62ABF5"
  }

  repository: "[internal]\nRepository" {
    style: {
      stroke-width: 5
    }
  }
  mapper: "[internal]\nMapper" {
    style: {
      stroke-width: 5
    }
  }
  mapper -> entity: {class: DependencyConnection}

  entity: "<<Kotlin Class>>\nEntity"

  persistenceAdapter: "[Internal]\n<<Kotlin Class>>\nPersistenceAdapter" {
    style: {
      stroke-width: 5
    }
  }
  persistenceAdapter -> repository: {class: DependencyConnection}
  persistenceAdapter -> mapper: {class: DependencyConnection}
}
application.persistenceAdapter -> core.persistencePort: {class: ImplementsConnection}
application.mapper -> core.model: {class: DependencyConnection}

infrastructure: Infrastructure {
  style: {
    fill: "#F5CBC4"
    stroke: "#F57662"
  }
}
infrastructure -> core.infraPort: {class: ImplementsConnection}
